{
 "title": "Fermentum Tanques",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tanque 1: SensorT1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT1\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 1: SensorT1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT1\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Rango de Temperatura SensorT1 (Tanque 1)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  minimo AS \"Temp. Mín\",\n  SensorT1,\n  maximo AS \"Temp Máx.\"\nFROM tanque1\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Estado de Alarma: Tanque 1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  Alarma\nFROM tanque1\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 2: SensorT2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT2\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 2: SensorT2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT2\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Rango de Temperatura del SensorT2 (Tanque 2)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  minimo AS \"Temp. Mín\",\n  SensorT2,\n  maximo AS \"Temp. Máx\"\nFROM tanque2\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Estado de Alarma: Tanque 2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  Alarma\nFROM tanque2\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 3: SensorT3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT3\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 3: SensorT3",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT3\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Rango de Temperatura del SensorT3 (Tanque 3)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  minimo AS \"Temp. Mín.\",\n  SensorT3,\n  maximo AS \"Temp. Máx\"\nFROM tanque3\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Estado de Alarma: Tanque 3",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  Alarma\nFROM tanque3\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 4: SensorT4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT4\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 4: SensorT4",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT4\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Rango de Temperatura del SensorT4 (Tanque 4)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  minimo AS \"Temp. Mín\",\n  SensorT4,\n  maximo AS \"Temp. Máx\"\nFROM tanque4\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Estado de Alarma: Tanque 4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  Alarma\nFROM tanque4\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 5: SensorT5",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT5\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 5: SensorT5",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT5\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Rango de Temperatura SensorT5 (Tanque 5)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  minimo AS \"Temp. Mín\",\n  SensorT5,\n  maximo AS \"Temp. Máx\"\nFROM tanque5\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Estado de Alarma: Tanque 5",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  avg(Alarma) AS \"Alarma\"\nFROM tanque5\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 6: SensorT6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT6\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 6: SensorT6",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT6\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Rango de Temperatura SensorT6 (Tanque 6)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  minimo AS \"Temp. Mín\",\n  SensorT6,\n  maximo AS \"Temp. Máx\"\nFROM tanque6\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Estado de Alarma: Tanque 6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  Alarma\nFROM tanque6\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 7: SensorT7",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  avg(SensorT7) AS \"SensorT7\"\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 7: SensorT7",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT7\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Rango de Temperatura SensorT7 (Tanque 7)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  minimo AS \"Temp. Mín\",\n  SensorT7,\n  maximo AS \"Temp. Máx\"\nFROM tanque7\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Estado de Alarma: Tanque 7",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  Alarma\nFROM tanque7\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 8: SensorT8",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT8\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 8: SensorT8",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT8\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Rango de Temperatura SensorT8 (Tanque 8)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  minimo AS \"Temp. Mín\",\n  SensorT8,\n  maximo AS \"Temp. Máx\"\nFROM tanque8\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Estado de Alarma: Tanque 8",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  Alarma\nFROM tanque8\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 9: SensorT9",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT9\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 9: SensorT9",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT8\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Rango de Temperatura SensorT9 (Tanque 9)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  minimo AS \"Temp. Mín\",\n  SensorT9,\n  maximo AS \"Temp. Máx\"\nFROM tanque9\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Estado de Alarma: Tanque 9",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  Alarma\nFROM tanque9\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 10: SensorT10",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT10\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Tanque 10: SensorT10",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  SensorT10\nFROM datos\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Rango de Temperatura SensorT10 (Tanque 10)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  minimo AS \"Temp. Mín\",\n  SensorT10,\n  maximo AS \"Temp. Máx\"\nFROM tanque10\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  },
  {
   "title": "Estado de Alarma: Tanque 10",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,10s),\n  Alarma\nFROM tanque10\nGROUP BY 1\nORDER BY $__timeGroup(fecha,10s)"
    }
   ]
  }
 ]
}